name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          # ติดตั้ง dependencies อื่นๆ ที่ต้องการ

      - name: Run script
        run: python script.py
